heat_template_version: 2014-10-16
#heat_template_version: 2015-10-15
description: Simple template to deploy a single compute instance

parameters:
  key_name:
    type: string
    label: Key Name
    description: Name of key-pair to be used for compute instance
    constraints:
      - custom_constraint: nova.keypair
  mysql_inst_type:
    type: string
    label: Instance Type
    default: m1.small
    constraints:
      - custom_constraint: nova.flavor
  hap_inst_type:
    type: string
    label: Instance Type
    default: m1.small
    constraints:
      - custom_constraint: nova.flavor
  public_network:
    type: string
    label: Public Network Name
    default: internal_floating_net

#  network:
#    type: string
#    label: Network where stack will reside
#    default: rj-private
#    constraints:
#      - custom_constraint: neutron.network

resources:

  private_network:
    type: lib/private_network.yaml
    properties:
     public_network: { get_param: public_network }

  mysql2:
#    type: rjj::mysql
    type: lib/mysql.yaml
    properties:
#      network: { get_param: network }
      network: { get_attr: [private_network, name] }
      instance_type: { get_param: mysql_inst_type }
      key_name: { get_param: key_name } 

  floating_ip1:
    type: lib/floating_ip.yaml
    properties:
      port: { get_attr: [mysql2, port] }
      public_network: { get_param: public_network }

  mysql1:
#    type: rjj::mysql
    type: lib/mysql.yaml
    properties:
#      network: { get_param: network }
      network: { get_attr: [private_network, name] }
      instance_type: { get_param: mysql_inst_type }
      key_name: { get_param: key_name } 
      
  floating_ip2:
    type: lib/floating_ip.yaml
    properties:
      port: { get_attr: [mysql1, port] }
      public_network: { get_param: public_network }

#outputs:
#  inst_name:
#    description: Name of the instance
#    value: { get_attr: [mysql_server, name] }
#  instance_ip:
#    description: IP address of the instance
#    value: { get_attr: [mysql_server, first_address] }
